import Header from "@/components/Header";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";
import "./globals.css";

import { Edu_VIC_WA_NT_Beginner, Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RobotoFont = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});
const EduViWaFont = Edu_VIC_WA_NT_Beginner({
  subsets: ["latin"],
  weight: ["600"],
  variable: "--font-edu-vic-wa",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body
        className={`${RobotoFont.variable} ${EduViWaFont.variable} antialiased`}
      >
        <SessionProvider>
          <Header />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
